name: firstdevoops
on: 
  push
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v4
      - name: dependency
        uses: actions/setup-dotnet@v4
      - name: restore
        run: dotnet restore Sample/Sample.csproj
      - name: test
        run: dotnet test Sample/Sample.csproj
      - name: build
        run: dotnet build Sample/Sample.csproj
      - name: publish
        run: dotnet publish Sample/Sample.csproj -c Release -o output
      - name: check
        run: |
          ls -la
          pwd 
          cd output
          ls -la
          pwd
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-apps-artifacts
          path: output
        
